# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NumpyToRender',
                'doc_host': 'https://cornusandu.github.io',
                'git_url': 'https://github.com/cornusandu/NumpyToRender',
                'lib_path': 'np2render'},
  'syms': {'np2render.core': {'np2render.core.create_array': ('core.html#create_array', 'np2render/core.py')}}}
