"""Allows for movement of cells / "entities" from one position to another."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_movement.ipynb.

# %% auto 0
__all__ = ['move_entity', 'move_up', 'move_down', 'move_left', 'move_right']

# %% ../nbs/01_movement.ipynb 3
import numpy as np

# %% ../nbs/01_movement.ipynb 4
def move_entity(array: np.ndarray, origpos: tuple[int, int], newpos: tuple[int, int], default: int = 0) -> np.ndarray:
    x1, y1 = origpos
    x2, y2 = newpos
    array[y2, x2] = array[y1, x1]
    array[y1, x1] = default
    return array

def move_up(array: np.ndarray, pos: tuple[int, int], default: int = 0) -> np.ndarray:
    return move_entity(array, pos, (pos[0], pos[1] - 1), default)

def move_down(array: np.ndarray, pos: tuple[int, int], default: int = 0) -> np.ndarray:
    return move_entity(array, pos, (pos[0], pos[1] + 1), default)

def move_left(array: np.ndarray, pos: tuple[int, int], default: int = 0) -> np.ndarray:
    return move_entity(array, pos, (pos[0] - 1, pos[1]), default)

def move_right(array: np.ndarray, pos: tuple[int, int], default: int = 0) -> np.ndarray:
    return move_entity(array, pos, (pos[0] + 1, pos[1]), default)
